version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d:ro

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails-app:/root/rails-app
    ports:
      - "3000:3000"
